name: BanMaster
main: pro.banmaster.bukkit.BanMasterPlugin
version: "0.0.1"
commands:
  banmaster:
    permission: "banmaster.banmaster"
  ban:
    permission: "banmaster.ban"
    aliases: ["tban"]
  gban:
    permission: "banmaster.gban"
  unban:
    permission: "banmaster.unban"
  whois:
    permission: "banmaster.whois"
    aliases: ["lookup", "bancheck"]
  warn:
    permission: "banmaster.warn"
    aliases: "warning"
  proof:
    permission: "banmaster.proof"
    aliases: ["sendproof"]